# ==============================
# Local Mosquitto Broker (dev)
# ==============================
listener 1883
allow_anonymous true

persistence true
persistence_location /mosquitto/data/

# ==============================
# Bridge: pull messages from test.mosquitto.org
# ==============================
connection bridge_from_testmosq
address test.mosquitto.org:1883

restart_timeout 5
try_private false
cleansession true
keepalive_interval 30

# Subscribe remote topic -> inject into local broker
topic farm/coffee-farm-01/device/node-01/sensors in 0

